import { defineField, defineType } from 'sanity'

export default defineType({
  name: 'project',
  title: 'Progetti',
  type: 'document',
  fieldsets: [
    {
      name: 'basic',
      title: 'Informazioni Base',
      options: { collapsible: false, collapsed: false },
    },
    {
      name: 'content',
      title: 'Contenuto',
      options: { collapsible: true, collapsed: false },
    },
    {
      name: 'display',
      title: 'Visualizzazione',
      options: { collapsible: true, collapsed: true },
    },
    {
      name: 'seo',
      title: 'SEO',
      options: { collapsible: true, collapsed: true },
    },
    {
      name: 'dashboard',
      title: 'Dashboard (Avanzato)',
      options: { collapsible: true, collapsed: true },
    },
  ],
  fields: [
    defineField({
      name: 'name',
      title: 'Nome del Progetto',
      type: 'string',
      validation: (Rule) => Rule.required(),
      fieldset: 'basic',
    }),
    defineField({
      name: 'title',
      title: 'Titolo (per compatibilità)',
      type: 'string',
      description: 'Campo per compatibilità - compila solo se necessario',
      fieldset: 'basic',
    }),
    defineField({
      name: 'slug',
      title: 'Slug',
      type: 'slug',
      options: {
        source: 'name',
        maxLength: 96,
      },
      validation: (Rule) => Rule.required(),
      fieldset: 'basic',
    }),
    defineField({
      name: 'description',
      title: 'Descrizione',
      type: 'text',
      rows: 3,
      description: 'Descrizione breve del progetto',
      fieldset: 'content',
    }),
    defineField({
      name: 'shortDescription',
      title: 'Descrizione Breve (per compatibilità)',
      type: 'text',
      description: 'Campo per compatibilità - compila solo se necessario',
      fieldset: 'content',
    }),
    defineField({
      name: 'fullDescription',
      title: 'Descrizione Completa',
      type: 'array',
      of: [
        {
          type: 'block',
          styles: [
            { title: 'Normal', value: 'normal' },
            { title: 'H2', value: 'h2' },
            { title: 'H3', value: 'h3' },
            { title: 'H4', value: 'h4' },
          ],
          lists: [
            { title: 'Bullet', value: 'bullet' },
            { title: 'Numbered', value: 'number' },
          ],
        },
      ],
      fieldset: 'content',
    }),
    defineField({
      name: 'mainImage',
      title: 'Immagine Principale',
      type: 'image',
      options: {
        hotspot: true,
      },
      description: 'Immagine principale del progetto (opzionale)',
      fieldset: 'content',
    }),
    defineField({
      name: 'gallery',
      title: 'Galleria Immagini',
      type: 'array',
      of: [
        {
          type: 'image',
          options: {
            hotspot: true,
          },
        },
      ],
      description: 'Galleria di immagini aggiuntive (opzionale)',
      fieldset: 'content',
    }),
    defineField({
      name: 'client',
      title: 'Cliente',
      type: 'string',
      description: 'Nome del cliente (opzionale)',
      fieldset: 'content',
    }),
    defineField({
      name: 'completionDate',
      title: 'Data di Completamento',
      type: 'date',
      description: 'Data di completamento del progetto (opzionale)',
      fieldset: 'content',
    }),
    defineField({
      name: 'technologies',
      title: 'Tecnologie Utilizzate',
      type: 'array',
      of: [{ type: 'string' }],
      description: 'Lista delle tecnologie utilizzate (opzionale)',
      fieldset: 'content',
    }),
    defineField({
      name: 'projectUrl',
      title: 'URL del Progetto',
      type: 'url',
      description: 'Link al progetto live (opzionale)',
      fieldset: 'content',
    }),
    defineField({
      name: 'githubUrl',
      title: 'URL GitHub',
      type: 'url',
      description: 'Link al repository GitHub (opzionale)',
      fieldset: 'content',
    }),
    defineField({
      name: 'service',
      title: 'Servizio Associato',
      type: 'reference',
      to: [{ type: 'service' }],
      description: 'Servizio associato a questo progetto (opzionale)',
      fieldset: 'content',
    }),
    defineField({
      name: 'assignedServices',
      title: 'Servizi Assegnati',
      type: 'array',
      of: [{ type: 'reference', to: [{ type: 'service' }] }],
      description: 'Servizi assegnati a questo progetto (opzionale)',
      fieldset: 'content',
    }),
    defineField({
      name: 'order',
      title: 'Ordine di Visualizzazione',
      type: 'number',
      description: 'Ordine in cui appare il progetto (numeri più bassi prima)',
      initialValue: 0,
      fieldset: 'display',
    }),
    defineField({
      name: 'isActive',
      title: 'Attivo',
      type: 'boolean',
      description: 'Mostra questo progetto sul sito',
      initialValue: true,
      fieldset: 'display',
    }),
    defineField({
      name: 'featured',
      title: 'Progetto in Evidenza',
      type: 'boolean',
      description: 'Mostra questo progetto come progetto in evidenza',
      initialValue: false,
      fieldset: 'display',
    }),
    defineField({
      name: 'isPublic',
      title: 'Pubblico',
      type: 'boolean',
      description: 'Se il progetto è visibile pubblicamente',
      initialValue: true,
      fieldset: 'display',
    }),
    defineField({
      name: 'metaTitle',
      title: 'Meta Title (SEO)',
      type: 'string',
      description: 'Titolo SEO per la pagina del progetto (opzionale)',
      fieldset: 'seo',
    }),
    defineField({
      name: 'metaDescription',
      title: 'Meta Description (SEO)',
      type: 'text',
      rows: 3,
      description: 'Descrizione SEO per la pagina del progetto (opzionale)',
      fieldset: 'seo',
    }),
    // ===== DASHBOARD FIELDS =====
    defineField({
      name: 'status',
      title: 'Stato del Progetto',
      type: 'string',
      options: {
        list: [
          { title: 'Attivo', value: 'active' },
          { title: 'Completato', value: 'completed' },
          { title: 'In Pausa', value: 'on-hold' },
          { title: 'Cancellato', value: 'cancelled' },
        ],
      },
      initialValue: 'active',
      fieldset: 'dashboard',
    }),
    defineField({
      name: 'priority',
      title: 'Priorità',
      type: 'string',
      options: {
        list: [
          { title: 'Alta', value: 'high' },
          { title: 'Media', value: 'medium' },
          { title: 'Bassa', value: 'low' },
        ],
      },
      initialValue: 'medium',
      fieldset: 'dashboard',
    }),
    defineField({
      name: 'budget',
      title: 'Budget (€)',
      type: 'number',
      description: 'Budget allocato per il progetto',
      initialValue: 0,
      fieldset: 'dashboard',
    }),
    defineField({
      name: 'actualCost',
      title: 'Costi Attuali (€)',
      type: 'number',
      description: 'Costi effettivamente sostenuti',
      initialValue: 0,
      fieldset: 'dashboard',
    }),
    defineField({
      name: 'expectedRevenue',
      title: 'Ricavi Attesi (€)',
      type: 'number',
      description: 'Ricavi attesi dal progetto',
      initialValue: 0,
      fieldset: 'dashboard',
    }),
    defineField({
      name: 'progress',
      title: 'Progresso (%)',
      type: 'number',
      description: 'Percentuale di completamento del progetto',
      initialValue: 0,
      validation: (Rule) => Rule.min(0).max(100),
      fieldset: 'dashboard',
    }),
    defineField({
      name: 'startDate',
      title: 'Data di Inizio',
      type: 'date',
      description: 'Data di inizio del progetto',
      fieldset: 'dashboard',
    }),
    defineField({
      name: 'endDate',
      title: 'Data di Fine',
      type: 'date',
      description: 'Data di fine prevista del progetto',
      fieldset: 'dashboard',
    }),
    defineField({
      name: 'team',
      title: 'Team',
      type: 'array',
      of: [{ type: 'string' }],
      description: 'Membri del team assegnati al progetto',
      fieldset: 'dashboard',
    }),
    defineField({
      name: 'notes',
      title: 'Note',
      type: 'text',
      rows: 4,
      description: 'Note aggiuntive sul progetto',
      fieldset: 'dashboard',
    }),
  ],
  preview: {
    select: {
      title: 'name',
      status: 'status',
      progress: 'progress',
      media: 'mainImage',
    },
    prepare(selection) {
      const { title, status, progress, media } = selection
      return {
        title: title,
        subtitle: `${status || 'N/A'} - ${progress || 0}% completato`,
        media: media,
      }
    },
  },
})
