import { defineField, defineType } from 'sanity'

export default defineType({
  name: 'service',
  title: 'Service',
  type: 'document',
  fieldsets: [
    {
      name: 'basic',
      title: 'Informazioni Base',
      options: { collapsible: false, collapsed: false },
    },
    {
      name: 'content',
      title: 'Contenuto',
      options: { collapsible: true, collapsed: false },
    },
    {
      name: 'display',
      title: 'Visualizzazione',
      options: { collapsible: true, collapsed: true },
    },
    {
      name: 'seo',
      title: 'SEO',
      options: { collapsible: true, collapsed: true },
    },
    {
      name: 'dashboard',
      title: 'Dashboard (Avanzato)',
      options: { collapsible: true, collapsed: true },
    },
  ],
  fields: [
    defineField({
      name: 'title',
      title: 'Nome del Servizio',
      type: 'string',
      validation: (Rule) => Rule.required(),
      fieldset: 'basic',
    }),
    defineField({
      name: 'name',
      title: 'Nome (per compatibilità)',
      type: 'string',
      description: 'Campo per compatibilità - compila solo se necessario, altrimenti usa il Nome del Servizio',
      fieldset: 'basic',
    }),
    defineField({
      name: 'slug',
      title: 'Service Slug',
      type: 'slug',
      options: {
        source: 'title',
        maxLength: 96,
      },
      validation: (Rule) => Rule.required(),
      fieldset: 'basic',
    }),
    defineField({
      name: 'description',
      title: 'Descrizione',
      type: 'text',
      description: 'Descrizione breve del servizio',
      fieldset: 'content',
    }),
    defineField({
      name: 'shortDescription',
      title: 'Descrizione Breve (per compatibilità)',
      type: 'text',
      description: 'Campo per compatibilità - compila solo se necessario, altrimenti usa la Descrizione',
      fieldset: 'content',
    }),
    defineField({
      name: 'fullDescription',
      title: 'Descrizione Completa',
      type: 'text',
      description: 'Descrizione dettagliata per la pagina del servizio (opzionale)',
      fieldset: 'content',
    }),
    defineField({
      name: 'icon',
      title: 'Icona',
      type: 'string',
      description: 'Emoji o identificatore icona (es. 🚀, ⚡)',
      fieldset: 'content',
    }),
    defineField({
      name: 'image',
      title: 'Immagine del Servizio',
      type: 'image',
      options: {
        hotspot: true,
      },
      description: 'Immagine per la card e la pagina del servizio (opzionale)',
      fieldset: 'content',
    }),
    defineField({
      name: 'features',
      title: 'Caratteristiche Principali',
      type: 'array',
      of: [{ type: 'string' }],
      description: 'Lista delle caratteristiche chiave (opzionale)',
      fieldset: 'content',
    }),
    defineField({
      name: 'url',
      title: 'URL del Servizio',
      type: 'url',
      description: 'Link alla pagina del servizio o URL esterno (opzionale)',
      fieldset: 'content',
    }),
    defineField({
      name: 'order',
      title: 'Ordine di Visualizzazione',
      type: 'number',
      description: 'Ordine in cui appare il servizio (numeri più bassi prima)',
      initialValue: 0,
      fieldset: 'display',
    }),
    defineField({
      name: 'isActive',
      title: 'Attivo',
      type: 'boolean',
      description: 'Mostra questo servizio sul sito',
      initialValue: true,
      fieldset: 'display',
    }),
    defineField({
      name: 'showInNavbar',
      title: 'Mostra nella Navbar',
      type: 'boolean',
      description: 'Includi questo servizio nel menu di navigazione',
      initialValue: true,
      fieldset: 'display',
    }),
    defineField({
      name: 'showInHomepage',
      title: 'Mostra in Homepage',
      type: 'boolean',
      description: 'Includi questo servizio nella sezione servizi della homepage',
      initialValue: true,
      fieldset: 'display',
    }),
    defineField({
      name: 'featured',
      title: 'In Evidenza',
      type: 'boolean',
      description: 'Mostra questo servizio come servizio in evidenza',
      initialValue: false,
      fieldset: 'display',
    }),
    defineField({
      name: 'metaTitle',
      title: 'Meta Title (SEO)',
      type: 'string',
      description: 'Titolo SEO per la pagina del servizio (opzionale)',
      fieldset: 'seo',
    }),
    defineField({
      name: 'metaDescription',
      title: 'Meta Description (SEO)',
      type: 'text',
      description: 'Descrizione SEO per la pagina del servizio (opzionale)',
      fieldset: 'seo',
    }),
    // ===== DASHBOARD FIELDS =====
    defineField({
      name: 'status',
      title: 'Stato del Servizio',
      type: 'string',
      options: {
        list: [
          { title: 'Attivo', value: 'active' },
          { title: 'Inattivo', value: 'inactive' },
          { title: 'Manutenzione', value: 'maintenance' },
          { title: 'Deprecato', value: 'deprecated' },
        ],
      },
      initialValue: 'active',
      fieldset: 'dashboard',
    }),
    defineField({
      name: 'category',
      title: 'Categoria',
      type: 'string',
      options: {
        list: [
          { title: 'Sviluppo', value: 'development' },
          { title: 'Design', value: 'design' },
          { title: 'Marketing', value: 'marketing' },
          { title: 'Consulenza', value: 'consulting' },
          { title: 'Supporto', value: 'support' },
        ],
      },
      fieldset: 'dashboard',
    }),
    defineField({
      name: 'price',
      title: 'Prezzo per Ora (€)',
      type: 'number',
      description: 'Prezzo orario del servizio',
      initialValue: 0,
      fieldset: 'dashboard',
    }),
    defineField({
      name: 'cost',
      title: 'Costo per Ora (€)',
      type: 'number',
      description: 'Costo orario del servizio',
      initialValue: 0,
      fieldset: 'dashboard',
    }),
    defineField({
      name: 'priceType',
      title: 'Tipo di Prezzo',
      type: 'string',
      options: {
        list: [
          { title: 'Ora', value: 'hour' },
          { title: 'Giorno', value: 'day' },
          { title: 'Progetto', value: 'project' },
          { title: 'Mese', value: 'month' },
        ],
      },
      initialValue: 'hour',
      fieldset: 'dashboard',
    }),
    defineField({
      name: 'hoursSold',
      title: 'Ore Vendute',
      type: 'number',
      description: 'Numero di ore vendute per questo servizio',
      initialValue: 0,
      fieldset: 'dashboard',
    }),
    defineField({
      name: 'revenue',
      title: 'Ricavi Totali (€)',
      type: 'number',
      description: 'Ricavi totali generati da questo servizio',
      initialValue: 0,
      fieldset: 'dashboard',
    }),
    defineField({
      name: 'margin',
      title: 'Margine (%)',
      type: 'number',
      description: 'Margine percentuale del servizio',
      initialValue: 0,
      fieldset: 'dashboard',
    }),
    defineField({
      name: 'plannedRevenue',
      title: 'Ricavi Pianificati (€)',
      type: 'number',
      description: 'Ricavi pianificati per questo servizio',
      initialValue: 0,
      fieldset: 'dashboard',
    }),
    defineField({
      name: 'actualRevenue',
      title: 'Ricavi Effettivi (€)',
      type: 'number',
      description: 'Ricavi effettivi generati da questo servizio',
      initialValue: 0,
      fieldset: 'dashboard',
    }),
    defineField({
      name: 'duration',
      title: 'Durata',
      type: 'string',
      description: 'Durata tipica del servizio (es. "2-4 settimane")',
      fieldset: 'dashboard',
    }),
    defineField({
      name: 'deliverables',
      title: 'Consegnabili',
      type: 'string',
      description: 'Cosa viene consegnato al cliente',
      fieldset: 'dashboard',
    }),
    defineField({
      name: 'availability',
      title: 'Disponibilità',
      type: 'string',
      description: 'Disponibilità del servizio (es. "Lun-Ven 9-18")',
      fieldset: 'dashboard',
    }),
    defineField({
      name: 'technologies',
      title: 'Tecnologie',
      type: 'array',
      of: [{ type: 'string' }],
      description: 'Tecnologie utilizzate per questo servizio',
      fieldset: 'dashboard',
    }),
    defineField({
      name: 'requirements',
      title: 'Requisiti',
      type: 'array',
      of: [{ type: 'string' }],
      description: 'Requisiti per utilizzare questo servizio',
      fieldset: 'dashboard',
    }),
    defineField({
      name: 'notes',
      title: 'Note',
      type: 'text',
      rows: 4,
      description: 'Note aggiuntive sul servizio',
      fieldset: 'dashboard',
    }),
    defineField({
      name: 'isPublic',
      title: 'Pubblico',
      type: 'boolean',
      initialValue: true,
      description: 'Se il servizio è visibile pubblicamente',
      fieldset: 'dashboard',
    }),
  ],
  preview: {
    select: {
      title: 'title',
      status: 'status',
      category: 'category',
      media: 'image',
    },
    prepare(selection) {
      const { title, status, category, media } = selection
      return {
        title: title,
        subtitle: `${status}${category ? ` - ${category}` : ''}`,
        media: media,
      }
    },
  },
})
